import React from 'react';
import { NextIntlClientProvider } from 'next-intl'; // Importa NextIntlClientProvider
import { getMessages } from 'next-intl/server'; // Importa getMessages
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ISUCI',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Proporciona todas las traducciones al cliente
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <Head>
        <title>ISUCI</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
        {/* Utiliza NextIntlClientProvider para proporcionar las traducciones */}
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
